name: tekartik_midi
version: 0.4.1
description: midi event and file parser
publish_to: none

environment:
  sdk: ^3.9.0
dependencies:
  collection: ">=1.18.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'

dev_dependencies:
  test: ">=1.24.0"
  path: ">=1.9.0"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.2'
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  build_web_compilers: ">=4.0.11"

